language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - 5.2

env:
  global:
    - DB_ENGINE=InnoDB
  matrix:
    - WP_VERSION=4.3
    - WP_VERSION=4.2.4
    - WP_VERSION=4.1.5
    - WP_VERSION=4.0.1
    - WP_VERSION=3.9
    - WP_VERSION=3.8
    - WP_VERSION=3.7
    - WP_VERSION=3.6
    - WP_VERSION=3.5
    - WP_VERSION=3.4
    - WP_VERSION=3.3
    - WP_VERSION=3.2

matrix:
  include:
    - php: 5.3
      env: DB_ENGINE=MyISAM DB_CHARSET=latin1 WP_UPGRADE=1
    - php: 5.4
      env: PLUGINS=akismet.3.1.1:jetpack.3.5:wordpress-seo.2.1.1:wordfence.5.3.12:contact-form-7.4.1.2:google-sitemap-generator.4.0.8
  allow_failures:
    - php: 5.2
      env: WP_VERSION=3.5
    - php: 5.2
      env: WP_VERSION=3.6
    - php: 5.2
      env: WP_VERSION=3.7

sudo: false

addons:
  hosts:
    - wpti.dev
  apt:
    packages:
      - nginx-light
      - heirloom-mailx

before_script:
  - tests/integration-environment/composer-update.sh
  - mysql -e 'create database wordpress;'
  - cd db
  - $TRAVIS_BUILD_DIR/vendor/bin/ruckus.php db:migrate
  - cd $TRAVIS_BUILD_DIR
  - tests/integration-environment/create.sh
  - cd $TRAVIS_BUILD_DIR/tests/mocha
  - npm install
  - cd $TRAVIS_BUILD_DIR
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/tests/mocha/node_modules/.bin/:$TRAVIS_BUILD_DIR/tests/integration-environment/

script:
  - vendor/bin/phpunit-php52
  - cd $TRAVIS_BUILD_DIR/tests/mocha && mocha-casperjs --timeout=360000

cache:
  directories:
    - vendor
    - tests/integration-environment/cache
    - tests/mocha/node_modules

after_failure:
  - free -ltm
  - cd $TRAVIS_BUILD_DIR/tests/mocha
  - ./debug-to-mail.sh a@ustimen.co 'Failed build dump' '/tmp/*.dmp'
  - ./debug-to-mail.sh a@ustimen.co 'Debug screenshots' '/tmp/*.screen.png'
